ingestion:
  has_header: true
  na_values: null
  read_excel: false
  separator: ','
  skiprows: null
  max_onehot_cardinality: 10
model:
  batch_size: 256
  epochs: 100
  learning_rate: 0.0002
  model_type: diffusion
  max_ram_gb: 8.0
privacy:
  enable_differential_privacy: true
  max_grad_norm: 1.0
  target_delta: 1.0e-05
  target_epsilon: 1.5
