columns:
- Administrative
- Administrative_Duration
- Informational
- Informational_Duration
- ProductRelated
- ProductRelated_Duration
- BounceRates
- ExitRates
- PageValues
- SpecialDay
- Month
- OperatingSystems
- Browser
- Region
- TrafficType
- VisitorType
- Weekend
- Revenue
has_header: true
pii_columns_to_drop: []
quasi_identifiers:
- OperatingSystems
- Browser
- Region
- TrafficType
- VisitorType
separator: ','
target_column: Revenue
