columns:
- age
- sex
- cp
- trestbps
- chol
- fbs
- restecg
- thalach
- exang
- oldpeak
- slope
- ca
- thal
- target
has_header: false
na_values:
- '?'
pii_columns_to_drop: []
quasi_identifiers:
- age
- sex
separator: ','
target_column: target
